version: '2'

services:
  php:
    container_name: shorturl_php
    build: ./docker/php/
    depends_on:
      - db
    links:
      - db
    environment:
      TIMEZONE: Europe/Kiev
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./:/var/www/shorturl
    working_dir: /var/www/shorturl

  webserver:
    container_name: shorturl_nginx
    image: nginx:1.11
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/shorturl.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 14540:80

  db:
    container_name: shorturlizer_db
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: shorturlizer
      MYSQL_DATABASE: shorturlizer_db
      MYSQL_USER: shorturlizer
      MYSQL_PASSWORD: shorturlizer
    ports:
      - 14520:3306